import type { EndpointDef, FieldMap } from '../types';

const locBus = (extra: FieldMap[] = []): FieldMap[] => [
  { column: 'loc_ref', sources: ['locRef', 'loc_ref'] },
  { column: 'bus_dt', sources: ['busDt', 'bus_dt'] },
  { column: 'rvc_num', sources: ['rvcNum'] },
  ...extra,
];

const qhKeys = (extra: FieldMap[] = []): FieldMap[] => [
  { column: 'loc_ref', sources: ['locRef', 'loc_ref'] },
  { column: 'bus_dt', sources: ['busDt', 'bus_dt'] },
  { column: 'clsd_bus_prd', sources: ['clsdBusPrd', 'busPrd', 'prd'] },
  { column: 'rvc_num', sources: ['rvcNum'] },
  ...extra,
];

const salesFields: FieldMap[] = [
  { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
  { column: 'itm_dsc_ttl', sources: ['itmDscTtl'] },
  { column: 'sub_dsc_ttl', sources: ['subDscTtl'] },
  { column: 'dsc_ttl', sources: ['dscTtl'] },
  { column: 'svc_ttl', sources: ['svcTtl'] },
  { column: 'non_rev_svc_ttl', sources: ['nonRevSvcTtl'] },
  { column: 'tax_coll_ttl', sources: ['taxCollTtl'] },
  { column: 'prep_cost_ttl', sources: ['prepCostTtl', 'prepCost'] },
  { column: 'chk_cnt', sources: ['chkCnt'] },
  { column: 'gst_cnt', sources: ['gstCnt'] },
  { column: 'sls_cnt', sources: ['slsCnt'] },
  { column: 'sls_qty', sources: ['slsQty'] },
  { column: 'rtn_cnt', sources: ['rtnCnt', 'rtrnCnt'] },
  { column: 'rtn_ttl', sources: ['rtnTtl', 'rtrnTtl'] },
  { column: 'vd_cnt', sources: ['vdCnt'] },
  { column: 'vd_ttl', sources: ['vdTtl'] },
];

const opsDailyFields: FieldMap[] = [
  ...locBus(),
  { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
  { column: 'itm_dsc_ttl', sources: ['itmDscTtl'] },
  { column: 'sub_dsc_ttl', sources: ['subDscTtl'] },
  { column: 'svc_ttl', sources: ['svcTtl'] },
  { column: 'non_rev_svc_ttl', sources: ['nonRevSvcTtl'] },
  { column: 'rtn_cnt', sources: ['rtnCnt', 'rtrnCnt'] },
  { column: 'rtn_ttl', sources: ['rtnTtl', 'rtrnTtl'] },
  { column: 'cred_ttl', sources: ['credTtl'] },
  { column: 'rnd_ttl', sources: ['rndTtl'] },
  { column: 'chng_in_grnd_ttl', sources: ['chngInGrndTtl'] },
  { column: 'non_txbl_sls_ttl', sources: ['nonTxblSlsTtl'] },
  { column: 'txbl_sls_ttl', sources: ['txblSlsTtl'] },
  { column: 'tax_exmpt_sls_ttl', sources: ['taxExmptSlsTtl'] },
  { column: 'tax_coll_ttl', sources: ['taxCollTtl'] },
  { column: 'sls_fcst', sources: ['slsFcst'] },
  { column: 'prep_cost_ttl', sources: ['prepCostTtl'] },
  { column: 'num_tbl', sources: ['numTbl'] },
  { column: 'tbl_turn_cnt', sources: ['tblTurnCnt'] },
  { column: 'chk_cnt', sources: ['chkCnt'] },
  { column: 'wait_pty_cnt', sources: ['waitPtyCnt'] },
  { column: 'wait_time_in_mins', sources: ['waitTimeInMins'] },
  { column: 'gst_cnt', sources: ['gstCnt'] },
  { column: 'dine_time_in_mins', sources: ['dineTimeInMins'] },
  { column: 'park_car_cnt', sources: ['parkCarCnt'] },
  { column: 'drv_thru_time_in_mins', sources: ['drvThruTimeInMins'] },
  { column: 'vd_ttl', sources: ['vdTtl'] },
  { column: 'vd_cnt', sources: ['vdCnt'] },
  { column: 'err_cor_ttl', sources: ['errCorTtl'] },
  { column: 'err_cor_cnt', sources: ['errCorCnt'] },
  { column: 'mngr_vd_ttl', sources: ['mngrVdTtl'] },
  { column: 'mngr_vd_cnt', sources: ['mngrVdCnt'] },
  { column: 'trans_cncl_ttl', sources: ['transCnclTtl'] },
  { column: 'trans_cncl_cnt', sources: ['transCnclCnt'] },
  { column: 'carryover_ttl', sources: ['carryoverTtl'] },
  { column: 'carryover_cnt', sources: ['carryoverCnt'] },
  { column: 'chk_opn_ttl', sources: ['chkOpnTtl'] },
  { column: 'chk_opn_cnt', sources: ['chkOpnCnt', 'chkOpnCount'] },
  { column: 'chk_xfer_in_ttl', sources: ['chkXferInTtl'] },
  { column: 'chk_xfer_in_cnt', sources: ['chkXferInCnt'] },
  { column: 'chk_xfer_out_ttl', sources: ['chkXferOutTtl'] },
  { column: 'chk_xfer_out_cnt', sources: ['chkXferOutCnt'] },
  { column: 'chk_clsd_ttl', sources: ['chkClsdTtl'] },
  { column: 'chk_clsd_cnt', sources: ['chkClsdCnt'] },
  { column: 'over_short_ttl', sources: ['overShortTtl'] },
  { column: 'no_sales_cnt', sources: ['noSalesCnt', 'noSlsCnt'] },
  { column: 'trn_chk_cnt', sources: ['trnChkCnt'] },
  { column: 'trn_chk_ttl', sources: ['trnChkTtl'] },
];

export const ENDPOINTS: EndpointDef[] = [
  {
    id: 'getOperationsDailyTotals',
    name: 'Operations Daily Totals',
    operation: 'getOperationsDailyTotals',
    category: 'daily',
    table: 'operations_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num'],
    fields: opsDailyFields,
  },
  {
    id: 'getComboItemDailyTotals',
    name: 'Combo Item Daily Totals',
    operation: 'getComboItemDailyTotals',
    category: 'daily',
    table: 'combo_item_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'comboItems',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'combo_mi_num'],
    fields: locBus([
      { column: 'combo_mi_num', sources: ['comboMiNum', 'miNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getControlDailyTotals',
    name: 'Control Daily Totals',
    operation: 'getControlDailyTotals',
    category: 'daily',
    table: 'control_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'controls',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'ctrl_name'],
    fields: locBus([
      { column: 'ctrl_name', sources: ['ctrlName', 'name'] },
      { column: 'ctrl_ttl', sources: ['ctrlTtl', 'ttl'] },
      { column: 'ctrl_cnt', sources: ['ctrlCnt', 'cnt'] },
    ]),
  },
  {
    id: 'getDiscountDailyTotals',
    name: 'Discount Daily Totals',
    operation: 'getDiscountDailyTotals',
    category: 'daily',
    table: 'discount_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'discounts',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'dsc_num'],
    fields: locBus([
      { column: 'dsc_num', sources: ['dscNum'] },
      { column: 'dsc_cnt', sources: ['dscCnt'] },
      { column: 'dsc_ttl', sources: ['dscTtl'] },
      { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
    ]),
  },
  {
    id: 'getEmployeeDailyTotals',
    name: 'Employee Daily Totals',
    operation: 'getEmployeeDailyTotals',
    category: 'daily',
    table: 'employee_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'employees',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'emp_num'],
    fields: locBus([
      { column: 'emp_num', sources: ['empNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getJobCodeDailyTotals',
    name: 'Job Code Daily Totals',
    operation: 'getJobCodeDailyTotals',
    category: 'daily',
    table: 'job_code_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'jobCodes',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'jc_num'],
    fields: locBus([
      { column: 'jc_num', sources: ['jcNum', 'jobCodeNum'] },
      { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
      { column: 'chk_cnt', sources: ['chkCnt'] },
      { column: 'gst_cnt', sources: ['gstCnt'] },
    ]),
  },
  {
    id: 'getMenuItemDailyTotals',
    name: 'Menu Item Daily Totals',
    operation: 'getMenuItemDailyTotals',
    category: 'daily',
    table: 'menu_item_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'menuItems',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'mi_num'],
    fields: locBus([
      { column: 'mi_num', sources: ['miNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getOrderChannelDailyTotals',
    name: 'Order Channel Daily Totals',
    operation: 'getOrderChannelDailyTotals',
    category: 'daily',
    table: 'order_channel_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'orderChannels',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'oc_num'],
    fields: locBus([
      { column: 'oc_num', sources: ['ocNum'] },
      { column: 'ot_num', sources: ['otNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getOrderTypeDailyTotals',
    name: 'Order Type Daily Totals',
    operation: 'getOrderTypeDailyTotals',
    category: 'daily',
    table: 'order_type_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'orderTypes',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'ot_num'],
    fields: locBus([
      { column: 'ot_num', sources: ['otNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getServiceChargeDailyTotals',
    name: 'Service Charge Daily Totals',
    operation: 'getServiceChargeDailyTotals',
    category: 'daily',
    table: 'service_charge_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'serviceCharges',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'svc_num'],
    fields: locBus([
      { column: 'svc_num', sources: ['svcNum'] },
      { column: 'svc_cnt', sources: ['svcCnt'] },
      { column: 'svc_ttl', sources: ['svcTtl'] },
    ]),
  },
  {
    id: 'getTaxDailyTotals',
    name: 'Tax Daily Totals',
    operation: 'getTaxDailyTotals',
    category: 'daily',
    table: 'tax_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'taxes',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'tax_num'],
    fields: locBus([
      { column: 'tax_num', sources: ['taxNum'] },
      { column: 'txbl_sls_ttl', sources: ['txblSlsTtl'] },
      { column: 'tax_coll_ttl', sources: ['taxCollTtl'] },
      { column: 'tax_exmpt_sls_ttl', sources: ['taxExmptSlsTtl'] },
    ]),
  },
  {
    id: 'getTenderMediaDailyTotals',
    name: 'Tender Media Daily Totals',
    operation: 'getTenderMediaDailyTotals',
    category: 'daily',
    table: 'tender_media_daily_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    itemArray: 'tenderMedias',
    uniqueKey: ['loc_ref', 'bus_dt', 'rvc_num', 'tm_num'],
    fields: locBus([
      { column: 'tm_num', sources: ['tmNum'] },
      { column: 'tnd_cnt', sources: ['tndCnt', 'cnt'] },
      { column: 'tnd_ttl', sources: ['tndTtl', 'ttl'] },
    ]),
  },
  {
    id: 'getComboItemQuarterHourTotals',
    name: 'Combo Item Quarter Hour Totals',
    operation: 'getComboItemQuarterHourTotals',
    category: 'quarterHour',
    table: 'combo_item_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'comboItems',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'combo_mi_num'],
    fields: qhKeys([
      { column: 'combo_mi_num', sources: ['comboMiNum', 'miNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getDiscountQuarterHourTotals',
    name: 'Discount Quarter Hour Totals',
    operation: 'getDiscountQuarterHourTotals',
    category: 'quarterHour',
    table: 'discount_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'discounts',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'dsc_num'],
    fields: qhKeys([
      { column: 'dsc_num', sources: ['dscNum'] },
      { column: 'dsc_cnt', sources: ['dscCnt'] },
      { column: 'dsc_ttl', sources: ['dscTtl'] },
    ]),
  },
  {
    id: 'getJobCodeQuarterHourTotals',
    name: 'Job Code Quarter Hour Totals',
    operation: 'getJobCodeQuarterHourTotals',
    category: 'quarterHour',
    table: 'job_code_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'jobCodes',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'jc_num'],
    fields: qhKeys([
      { column: 'jc_num', sources: ['jcNum', 'jobCodeNum'] },
      { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
      { column: 'chk_cnt', sources: ['chkCnt'] },
      { column: 'gst_cnt', sources: ['gstCnt'] },
    ]),
  },
  {
    id: 'getMenuItemQuarterHourTotals',
    name: 'Menu Item Quarter Hour Totals',
    operation: 'getMenuItemQuarterHourTotals',
    category: 'quarterHour',
    table: 'menu_item_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'menuItems',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'mi_num'],
    fields: qhKeys([
      { column: 'mi_num', sources: ['miNum'] },
      ...salesFields,
    ]),
  },
  {
    id: 'getOperationsQuarterHourTotals',
    name: 'Operations Quarter Hour Totals',
    operation: 'getOperationsQuarterHourTotals',
    category: 'quarterHour',
    table: 'operations_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num'],
    fields: qhKeys([
      { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
      { column: 'itm_dsc_ttl', sources: ['itmDscTtl'] },
      { column: 'sub_dsc_ttl', sources: ['subDscTtl'] },
      { column: 'svc_ttl', sources: ['svcTtl'] },
      { column: 'non_rev_svc_ttl', sources: ['nonRevSvcTtl'] },
      { column: 'chk_cnt', sources: ['chkCnt'] },
      { column: 'gst_cnt', sources: ['gstCnt'] },
      { column: 'vd_ttl', sources: ['vdTtl'] },
      { column: 'vd_cnt', sources: ['vdCnt'] },
    ]),
  },
  {
    id: 'getOrderTypeQuarterHourTotals',
    name: 'Order Type Quarter Hour Totals',
    operation: 'getOrderTypeQuarterHourTotals',
    category: 'quarterHour',
    table: 'order_type_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'orderTypes',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'ot_num'],
    fields: qhKeys([
      { column: 'ot_num', sources: ['otNum'] },
      { column: 'net_sls_ttl', sources: ['netSlsTtl'] },
      { column: 'chk_cnt', sources: ['chkCnt'] },
      { column: 'gst_cnt', sources: ['gstCnt'] },
    ]),
  },
  {
    id: 'getServiceChargeQuarterHourTotals',
    name: 'Service Charge Quarter Hour Totals',
    operation: 'getServiceChargeQuarterHourTotals',
    category: 'quarterHour',
    table: 'service_charge_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'serviceCharges',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'svc_num'],
    fields: qhKeys([
      { column: 'svc_num', sources: ['svcNum'] },
      { column: 'svc_cnt', sources: ['svcCnt'] },
      { column: 'svc_ttl', sources: ['svcTtl'] },
    ]),
  },
  {
    id: 'getTenderMediaQuarterHourTotals',
    name: 'Tender Media Quarter Hour Totals',
    operation: 'getTenderMediaQuarterHourTotals',
    category: 'quarterHour',
    table: 'tender_media_qh_totals',
    kind: 'totals',
    rvcArray: 'revenueCenters',
    periodArray: 'quarterHours',
    itemArray: 'tenderMedias',
    uniqueKey: ['loc_ref', 'bus_dt', 'clsd_bus_prd', 'rvc_num', 'tm_num'],
    fields: qhKeys([
      { column: 'tm_num', sources: ['tmNum'] },
      { column: 'tnd_cnt', sources: ['tndCnt', 'cnt'] },
      { column: 'tnd_ttl', sources: ['tndTtl', 'ttl'] },
    ]),
  },
  {
    id: 'getLocationDimensions',
    name: 'Location Dimensions',
    operation: 'getLocationDimensions',
    category: 'definition',
    table: 'location_dimensions',
    kind: 'definition',
    rootArray: 'locations',
    uniqueKey: ['loc_ref'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'name', sources: ['name'] },
      { column: 'open_dt', sources: ['openDt'] },
      { column: 'active', sources: ['active'] },
      { column: 'src_name', sources: ['srcName'] },
      { column: 'src_ver', sources: ['srcVer'] },
      { column: 'tz', sources: ['tz'] },
      { column: 'curr', sources: ['curr'] },
      { column: 'addr_ln1', sources: ['addrLn1'] },
      { column: 'addr_ln2', sources: ['addrLn2'] },
    ],
  },
  {
    id: 'getLatestBusDt',
    name: 'Latest Business Date',
    operation: 'getLatestBusDt',
    category: 'definition',
    table: 'latest_business_dates',
    kind: 'latestBusDt',
    uniqueKey: ['loc_ref'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'latest_bus_dt', sources: ['latestBusDt'] },
      { column: 'cur_utc', sources: ['curUTC', 'curUtc'] },
    ],
  },
  {
    id: 'getRevenueCenterDimensions',
    name: 'Revenue Center Dimensions',
    operation: 'getRevenueCenterDimensions',
    category: 'definition',
    table: 'revenue_center_dimensions',
    kind: 'definition',
    rootArray: 'revenueCenters',
    uniqueKey: ['loc_ref', 'rvc_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'rvc_num', sources: ['rvcNum'] },
      { column: 'name', sources: ['name', 'rvcName'] },
      { column: 'active', sources: ['active'] },
    ],
  },
  {
    id: 'getMenuItemDimensions',
    name: 'Menu Item Dimensions',
    operation: 'getMenuItemDimensions',
    category: 'definition',
    table: 'menu_item_dimensions',
    kind: 'definition',
    rootArray: 'menuItems',
    uniqueKey: ['loc_ref', 'mi_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'mi_num', sources: ['miNum'] },
      { column: 'name', sources: ['name', 'miName'] },
      { column: 'maj_grp_num', sources: ['majGrpNum'] },
      { column: 'fam_grp_num', sources: ['famGrpNum'] },
      { column: 'active', sources: ['active'] },
    ],
  },
  {
    id: 'getMenuItemPrices',
    name: 'Menu Item Prices',
    operation: 'getMenuItemPrices',
    category: 'definition',
    table: 'menu_item_prices',
    kind: 'definition',
    rootArray: 'menuItemPrices',
    uniqueKey: ['loc_ref', 'mi_num', 'price_seq'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'mi_num', sources: ['miNum'] },
      { column: 'price_seq', sources: ['priceSeq', 'seq'] },
      { column: 'price', sources: ['price'] },
      { column: 'effective_from', sources: ['effectiveFrom', 'effFrom'] },
      { column: 'effective_to', sources: ['effectiveTo', 'effTo'] },
    ],
  },
  {
    id: 'getDiscountDimensions',
    name: 'Discount Dimensions',
    operation: 'getDiscountDimensions',
    category: 'definition',
    table: 'discount_dimensions',
    kind: 'definition',
    rootArray: 'discounts',
    uniqueKey: ['loc_ref', 'dsc_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'dsc_num', sources: ['dscNum'] },
      { column: 'name', sources: ['name'] },
      { column: 'active', sources: ['active'] },
    ],
  },
  {
    id: 'getEmployeeDimensions',
    name: 'Employee Dimensions',
    operation: 'getEmployeeDimensions',
    category: 'definition',
    table: 'employee_dimensions',
    kind: 'definition',
    rootArray: 'employees',
    uniqueKey: ['loc_ref', 'emp_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'emp_num', sources: ['empNum'] },
      { column: 'first_name', sources: ['fName', 'firstName'] },
      { column: 'last_name', sources: ['lName', 'lastName'] },
      { column: 'payroll_id', sources: ['payrollID', 'payrollId'] },
      { column: 'active', sources: ['active'] },
    ],
  },
  {
    id: 'getJobCodeDimensions',
    name: 'Job Code Dimensions',
    operation: 'getJobCodeDimensions',
    category: 'definition',
    table: 'job_code_dimensions',
    kind: 'definition',
    rootArray: 'jobCodes',
    uniqueKey: ['loc_ref', 'jc_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'jc_num', sources: ['jcNum', 'jobCodeNum'] },
      { column: 'name', sources: ['name'] },
      { column: 'labor_cat', sources: ['laborCat', 'labCat'] },
    ],
  },
  {
    id: 'getOrderChannelDimensions',
    name: 'Order Channel Dimensions',
    operation: 'getOrderChannelDimensions',
    category: 'definition',
    table: 'order_channel_dimensions',
    kind: 'definition',
    rootArray: 'orderChannels',
    uniqueKey: ['loc_ref', 'oc_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'oc_num', sources: ['ocNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getOrderTypeDimensions',
    name: 'Order Type Dimensions',
    operation: 'getOrderTypeDimensions',
    category: 'definition',
    table: 'order_type_dimensions',
    kind: 'definition',
    rootArray: 'orderTypes',
    uniqueKey: ['loc_ref', 'ot_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'ot_num', sources: ['otNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getReasonCodeDimensions',
    name: 'Reason Code Dimensions',
    operation: 'getReasonCodeDimensions',
    category: 'definition',
    table: 'reason_code_dimensions',
    kind: 'definition',
    rootArray: 'reasonCodes',
    uniqueKey: ['loc_ref', 'rsn_code_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'rsn_code_num', sources: ['rsnCodeNum', 'rsnNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getServiceChargeDimensions',
    name: 'Service Charge Dimensions',
    operation: 'getServiceChargeDimensions',
    category: 'definition',
    table: 'service_charge_dimensions',
    kind: 'definition',
    rootArray: 'serviceCharges',
    uniqueKey: ['loc_ref', 'svc_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'svc_num', sources: ['svcNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getTaxDimensions',
    name: 'Tax Dimensions',
    operation: 'getTaxDimensions',
    category: 'definition',
    table: 'tax_dimensions',
    kind: 'definition',
    rootArray: 'taxes',
    uniqueKey: ['loc_ref', 'tax_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'tax_num', sources: ['taxNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getTenderMediaDimensions',
    name: 'Tender Media Dimensions',
    operation: 'getTenderMediaDimensions',
    category: 'definition',
    table: 'tender_media_dimensions',
    kind: 'definition',
    rootArray: 'tenderMedias',
    uniqueKey: ['loc_ref', 'tm_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'tm_num', sources: ['tmNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getCashierDimensions',
    name: 'Cashier Dimensions',
    operation: 'getCashierDimensions',
    category: 'definition',
    table: 'cashier_dimensions',
    kind: 'definition',
    rootArray: 'cashiers',
    uniqueKey: ['loc_ref', 'cashier_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'cashier_num', sources: ['cashierNum', 'empNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getCashManagementItemDimensions',
    name: 'Cash Management Item Dimensions',
    operation: 'getCashManagementItemDimensions',
    category: 'definition',
    table: 'cash_management_item_dimensions',
    kind: 'definition',
    rootArray: 'cmItems',
    uniqueKey: ['loc_ref', 'cm_item_num'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'cm_item_num', sources: ['cmItemNum'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getPaymentAccountHolderDimensions',
    name: 'Payment Account Holders',
    operation: 'getPaymentAccountHolderDimensions',
    category: 'definition',
    table: 'payment_account_holder_dimensions',
    kind: 'definition',
    rootArray: 'accountHolders',
    uniqueKey: ['loc_ref', 'acct_holder_id'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'acct_holder_id', sources: ['acctHolderId', 'id'] },
      { column: 'name', sources: ['name'] },
    ],
  },
  {
    id: 'getPaymentAccountDimensions',
    name: 'Payment Account Dimensions',
    operation: 'getPaymentAccountDimensions',
    category: 'definition',
    table: 'payment_account_dimensions',
    kind: 'definition',
    rootArray: 'accounts',
    uniqueKey: ['loc_ref', 'acct_id'],
    fields: [
      { column: 'loc_ref', sources: ['locRef'] },
      { column: 'acct_id', sources: ['acctId', 'id'] },
      { column: 'name', sources: ['name'] },
    ],
  },
];

export function getEndpoint(id: string) {
  return ENDPOINTS.find((e) => e.id === id);
}

export function endpointsByCategory() {
  return {
    daily: ENDPOINTS.filter((e) => e.category === 'daily'),
    quarterHour: ENDPOINTS.filter((e) => e.category === 'quarterHour'),
    definition: ENDPOINTS.filter((e) => e.category === 'definition'),
  };
}
