-- Operations daily totals: one row per location, business date, and revenue center.
-- Source: POST /bi/v1/{orgIdentifier}/getOperationsDailyTotals

CREATE TABLE IF NOT EXISTS operations_daily_totals (
    loc_ref              text        NOT NULL,
    bus_dt               date        NOT NULL,
    rvc_num              integer     NOT NULL,
    net_sls_ttl          numeric,
    itm_dsc_ttl          numeric,
    sub_dsc_ttl          numeric,
    svc_ttl              numeric,
    non_rev_svc_ttl      numeric,
    rtn_cnt              integer,
    rtn_ttl              numeric,
    cred_ttl             numeric,
    rnd_ttl              numeric,
    chng_in_grnd_ttl     numeric,
    non_txbl_sls_ttl     numeric,
    txbl_sls_ttl         numeric,
    tax_exmpt_sls_ttl    numeric,
    tax_coll_ttl         numeric,
    sls_fcst             numeric,
    prep_cost_ttl        numeric,
    num_tbl              integer,
    tbl_turn_cnt         integer,
    chk_cnt              integer,
    wait_pty_cnt         integer,
    wait_time_in_mins    numeric,
    gst_cnt              integer,
    dine_time_in_mins    numeric,
    park_car_cnt         integer,
    drv_thru_time_in_mins numeric,
    vd_ttl               numeric,
    vd_cnt               integer,
    err_cor_ttl          numeric,
    err_cor_cnt          integer,
    mngr_vd_ttl          numeric,
    mngr_vd_cnt          integer,
    trans_cncl_ttl       numeric,
    trans_cncl_cnt       integer,
    carryover_ttl        numeric,
    carryover_cnt        integer,
    chk_opn_ttl          numeric,
    chk_opn_cnt          integer,
    chk_xfer_in_ttl      numeric,
    chk_xfer_in_cnt      integer,
    chk_xfer_out_ttl     numeric,
    chk_xfer_out_cnt     integer,
    chk_clsd_ttl         numeric,
    chk_clsd_cnt         integer,
    over_short_ttl       numeric,
    no_sales_cnt         integer,
    trn_chk_cnt          integer,
    trn_chk_ttl          numeric,
    synced_at            timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (loc_ref, bus_dt, rvc_num)
);
